// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("char_ger_zombcrawl_body1_1");
	self.voice = "german";
	self.torsoDmg1 = "char_ger_zombcrawl_body1_g_upclean";
	self.torsoDmg2 = "char_ger_zombcrawl_body1_g_rarmoff_1";
	self.torsoDmg3 = "char_ger_zombcrawl_body1_g_larmoff_1";
	self.torsoDmg4 = "char_ger_zombcrawl_body1_g_torso_1";
	self.torsoDmg5 = "char_ger_zombcrawl_body1_g_behead";
	self.legDmg1 = "char_ger_zombcrawl_body1_g_lowclean";
	self.legDmg2 = "char_ger_zombcrawl_body1_g_rlegoff_1";
	self.legDmg3 = "char_ger_zombcrawl_body1_g_llegoff_1";
	self.legDmg4 = "char_ger_zombcrawl_body1_g_legsoff_1";
	self.gibSpawn1 = "char_ger_zombcrawl_body1_g_rarmspawn";
	self.gibSpawnTag1 = "J_Elbow_RI";
	self.gibSpawn2 = "char_ger_zombcrawl_body1_g_larmspawn";
	self.gibSpawnTag2 = "J_Elbow_LE";
	self.gibSpawn3 = "char_ger_zombcrawl_body1_g_rlegspawn";
	self.gibSpawnTag3 = "J_Knee_RI";
	self.gibSpawn4 = "char_ger_zombcrawl_body1_g_llegspawn";
	self.gibSpawnTag4 = "J_Knee_LE";
}

precache()
{
	precacheModel("char_ger_zombcrawl_body1_1");
	precacheModel("char_ger_zombcrawl_body1_g_upclean");
	precacheModel("char_ger_zombcrawl_body1_g_rarmoff_1");
	precacheModel("char_ger_zombcrawl_body1_g_larmoff_1");
	precacheModel("char_ger_zombcrawl_body1_g_torso_1");
	precacheModel("char_ger_zombcrawl_body1_g_behead");
	precacheModel("char_ger_zombcrawl_body1_g_lowclean");
	precacheModel("char_ger_zombcrawl_body1_g_rlegoff_1");
	precacheModel("char_ger_zombcrawl_body1_g_llegoff_1");
	precacheModel("char_ger_zombcrawl_body1_g_legsoff_1");
	precacheModel("char_ger_zombcrawl_body1_g_rarmspawn");
	precacheModel("char_ger_zombcrawl_body1_g_larmspawn");
	precacheModel("char_ger_zombcrawl_body1_g_rlegspawn");
	precacheModel("char_ger_zombcrawl_body1_g_llegspawn");
	precacheModel("char_ger_zombcrawl_body1_g_upclean");
	precacheModel("char_ger_zombcrawl_body1_g_rarmoff_1");
	precacheModel("char_ger_zombcrawl_body1_g_larmoff_1");
	precacheModel("char_ger_zombcrawl_body1_g_torso_1");
	precacheModel("char_ger_zombcrawl_body1_g_behead");
	precacheModel("char_ger_zombcrawl_body1_g_lowclean");
	precacheModel("char_ger_zombcrawl_body1_g_rlegoff_1");
	precacheModel("char_ger_zombcrawl_body1_g_llegoff_1");
	precacheModel("char_ger_zombcrawl_body1_g_legsoff_1");
	precacheModel("char_ger_zombcrawl_body1_g_rarmspawn");
	precacheModel("char_ger_zombcrawl_body1_g_larmspawn");
	precacheModel("char_ger_zombcrawl_body1_g_rlegspawn");
	precacheModel("char_ger_zombcrawl_body1_g_llegspawn");
}
