// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\char_ger_wrmcht_dronealias::main());
	self.voice = "german";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\char_ger_wrmcht_dronealias::main());
}
