// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\char_rus_guard_dronealias::main());
	self.voice = "russian";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\char_rus_guard_dronealias::main());
}
