// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_ger_wermacht_drone1";
	a[1] = "char_ger_wermacht_drone2";
	a[2] = "char_ger_wermacht_drone3";
	a[3] = "char_ger_wermacht_drone4";
	a[4] = "char_ger_wermacht_drone5";
	a[5] = "char_ger_wermacht_drone6";
	return a;
}
