// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_ger_waffenz_head1_2";
	a[1] = "char_ger_waffenz_head2_2";
	a[2] = "char_ger_waffenz_head3_2";
	a[3] = "char_ger_waffenz_head4_2";
	return a;
}
