// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_usa_marine_body1_1";
	a[1] = "char_usa_marine_body1_2";
	a[2] = "char_usa_marine_body2_1";
	a[3] = "char_usa_marine_body2_2";
	return a;
}
