// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_ger_waffenz_head1_1";
	a[1] = "char_ger_waffenz_head2_1";
	a[2] = "char_ger_waffenz_head3_1";
	a[3] = "char_ger_waffenz_head4_1";
	return a;
}
