// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_ger_wermacht_helm_cloth1";
	a[1] = "char_ger_wermacht_helm1";
	a[2] = "char_ger_wermacht_helm_strap1";
	a[3] = "char_ger_wermacht_helm_wire1";
	return a;
}
