// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_ger_pnzrgren_gear1";
	a[1] = "char_ger_pnzrgren_gear2";
	a[2] = "char_ger_pnzrgren_gear3";
	a[3] = "char_ger_pnzrgren_gear4";
	return a;
}
