// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_rus_guard_body1_drone1";
	a[1] = "char_rus_guard_body1_drone2";
	a[2] = "char_rus_guard_body1_drone3";
	a[3] = "char_rus_guard_body1_drone4";
	a[4] = "char_rus_guard_body1_drone5";
	a[5] = "char_rus_guard_body1_drone6";
	a[6] = "char_rus_guard_body1_drone7";
	a[7] = "char_rus_guard_body1_drone8";
	return a;
}
